### PR TITLE
Fix for subclassing more than once from Model

### PR DESCRIPTION
**Pull request by acofer**
Hi! We have a base class off of Bookshelf.Model, and our other models `.extend()` that. I made a small fix to allow this. I brought in lodash to make it look more like bookshelf's `extend`, but it could probably be done without if you prefer.

### CODE REVIEW

**Comment by bogus34** [comment]
Hello!
Could you provide simple test-case that failed and now fixed with your PR? Or just an example of code that didn't works.
Thanks for contributing!

**Comment by acofer** [comment]
Sure thing! In our case, it fails if there is a constructor defined on a base Model that is supposed to run. Note: the idiomatic coffeescript constructor `super` call does not work in this case because Bookshelf uses its own `extend()` instead of proper `extends` subclassing, so I used `db.Model.apply this, arguments`.

**Comment by bogus34** [comment]
Cool, thanks! I'll merge it in several days.

**Comment by bogus34** [comment]
Hello!
I've decided to apply your fix for model extending in a slightly different way, though your test case is passing.
Thanks again!

**Pull request closed without merging**
